# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: main
    
permissions:
  contents: read
  pull-requests: write
  
jobs:
  publish-gpr:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v2
        with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: '@prasad-vss'
      - run: npm install
      - run: npm install win-node-env
      - run: npm run build
      - run: npm uninstall win-node-env
      - run: cd dist
      - run: npm publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
